# Site
name: "Dorsikret"
title: "Dorsikret"
description: "Timeless Beauty, Everyday. Enhance your natural beauty with expert tips, tutorials, and the latest trends. Embrace inner and outer beauty daily."
logo: '/favicon.ico'
favicon: '/favicon.ico'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
     name: Rais Fazriansyah
     display_name: Rais Fazriansyah
     gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi9F4mwNwQpn8ySIwM04R_xdW78rEqCgAPQwptAIfCKwFqgHPzWI-93Qi9n9ydhmxyc0IRf9fR6URJXMa1uwn-HWoI53OdY2cqcL31qRCF_QEjo5La1aFVKxMyftApuIFJ3lWm38eqLQDhO-kLQFEttSL2YbUgB3hZONXMuxKFpxF-XCyrbklgTbR_lVII/s1600/20240928_224124.jpg
     email: r.fazriansyah@gmail.com
     web: /aboutme
     twitter: https://twitter.com/wowthemesnet
     description: "Writing opens windows to the depths of the soul revealing layers of truth and emotion that often go unnoticed in everyday life"
  admin2:
     name: Yessi Amanda Clara
     display_name: Yessi Amanda Clara
     gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEivwo_RIBiWT6QKhSzsg0j_dpBnsulFU0zgGjtuGwE-v3VudMrY4Rk1KmjumNW32jd1hG0j2akSU02QyoRLEfE62FCRlXrA8M8oit_oNXoekXwX1fWYg5xjAo4cbZAiyiFvPlcUNEG6TjjBaxEOwLIwISOitED9KWhpJchmw7y2kf_x8j5IkJt-edCnUTk/s1600/20241009_134205.jpg
     email: kuliaridijebor33@gmail.com
     web: /aboutme2
     twitter: https://twitter.com/wowthemesnet
     description: "To write is to embark on a journey of discovery where each sentence uncovers not only what we know but what we have yet to realize"
  admin3:
     name: Tania Shakila
     display_name: Tania Shakila
     gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEggO4QQd25sXKq4_CQSNXU4J_JxvEWIkCI0VvlqL45zPOVv_fC744eeLsR-p3KuKf02NwmkubE7E5oi34AKNWNnN30xtDHUIIdFxv34DegR2CYXNyHv0RiQVMfG4P3vgsJHSr_2SCFbZDRaJ6WQ2tiyf24lMuKAt65cUFcVSZ7q-caMt1Bf8S_yC4BWAYw/s1600/20241009_134149.jpg
     email: tengtengteng044@gmail.com
     web: /aboutme3
     twitter: https://twitter.com/wowthemesnet
     description: "I write to unravel the stories hidden within my heart, weaving them into the tapestry of my life"
  admin4:
     name: Nesya Rivania
     display_name: Nesya Rivania
     gravatar: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEga0vwOnTPayuTZaRvubJhRC8AQZabXnSpH2GO3e-imGInmYZz2HEvS_70Or9mjuzv3Aan8HOutnNR-YObwmbBJYqxjcfEls_B_TL477hHSPTUTS-7-TsVIptcYuhh5WQ0f_APdLxkkxEBvEbHXXh_jOX7vqDNcvzQJguvNWfIyANud3MLPOgdK1CtgHLw/s1600/20241009_134129.jpg"
     email: eweuhsasaha92@gmail.com
     web: /aboutme4
     twitter: https://twitter.com/wowthemesnet
     description: "With every story told a new world is crafted and through the act of writing we breathe life into dreams ideas and possibilities"
  admin5:
     name: Kania Naava
     display_name: Kania Naava
     gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhL8SutW3gNcw1F8PBShGY9RsbRPEuHm-lbHYW3pNJZtfuWyNtpTWR2F5KmTTZ-fqYS4qm36W3s5Tl-083OKl9E_9bFj9lmM6pqW6aH8dJwvT0cuaJO9pR-C2ic8IL3NeXqH_0E0RTXGAmQ6eIr-N_ZEffSE6DfUfcGW5TiKjjsCIFos-Wpht4HVsfAVpE/s1600/20241009_134057.jpg
     email: masauntukoranglain33@gmail.com
     web: /aboutme5
     twitter: https://twitter.com/wowthemesnet
     description: "While words may flow freely it is the ideas behind them that stand the test of time shaping the future and preserving the past"
  admin6:
    name: Amira Putri
    display_name: Amira Putri
    gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEheOu3m3fi67hTWv_gxAz0szEbVN_072xk-E2q9zckYp1A5b3gZJkIBB2pbFKMR9k0d3x5SNDNS34VP7UIv1g9b7VXINRvqHkdt8mDj45nfkaDFtBlJfbjkU5k1U5UdR5tyVtq0mROrGsownZ41ckR_XwPoFZgk9RDIeC5mhQmAEzI6lB3CYiMUFS2j360/s1600/20241009_134112.jpg
    email: jebormitra@gmail.com
    web: /aboutme6
    twitter: https://twitter.com/wowthemesnet
    description: "The true value of writing is not found in how much is said but in how deeply it resonates with the reader's heart and mind"
  admin7:
    name: Hana Alesha
    display_name: Hana Alesha
    gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhor-vM2A8HXcfhtHJAfSozeFBWeJV_WPN5bX4z2fY5NUujZqbVwElvwA6JDg7dLtvZFzInHR1PXYtujSk7d-iyUJYjIugWCyYvYvn05sVnxHmi2v6_B98xNC8iJRZ74zidvBlBCEsgsdyoNhvbtFzrXUeVrEy9Zbo601Z77udlt189JVLBKlRhPqPZPXI/s1600/20241009_134032.jpg
    email: ogehtunduh561@gmail.com
    web: /aboutme7
    twitter: https://twitter.com/wowthemesnet
    description: "A writer has the unique ability to capture the fleeting essence of a moment preserving it in words long after time has moved on"
  admin8:
    name: Irena Nabella
    display_name: Irena Nabella
    gravatar: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjn1yRlIatNyPbAfohi72Iye9hAFyNlUQfYbcsGv7804BJzXYusAx9kY39cGzbjErzw64BDtBJq6K1IQ8iU7_Pf8hlPKl2_ZwIsDw55GmSTwLztdFEX0tzs-sT2deR-okGq_yg9hsRaEJ8KCJwVZB_MMdSWKflgNewGbuVllJLB3rJKqzx3OTdp0riqrj4/s1600/20241009_134018.jpg
    email: hawangancileubak@gmail.com
    web: /aboutme8
    twitter: https://twitter.com/wowthemesnet
    description: "Writing is not merely about reaching a destination it is about embracing the twists and turns of the creative journey learning and growing with every word"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
